// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    ADivider: typeof import('@arco-design/web-vue')['Divider']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputNumber: typeof import('@arco-design/web-vue')['InputNumber']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    AOption: typeof import('@arco-design/web-vue')['Option']
    ASelect: typeof import('@arco-design/web-vue')['Select']
    ASplit: typeof import('@arco-design/web-vue')['Split']
    ATable: typeof import('@arco-design/web-vue')['Table']
    ATypographyParagraph: typeof import('@arco-design/web-vue')['TypographyParagraph']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ProjectItem: typeof import('./src/components/ProjectItem.vue')['default']
    ProjectNav: typeof import('./src/components/ProjectNav.vue')['default']
    SystemNavBar: typeof import('./src/components/SystemNavBar.vue')['default']
    TableDataMock: typeof import('./src/components/TableDataMock.vue')['default']
    Tables: typeof import('./src/components/Tables.vue')['default']
  }
}

export { }
